# Generated by Django 5.0 on 2024-02-09 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
    ]
