# Generated by Django 5.0 on 2024-02-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_remove_evento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='aprovada',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='sala',
        ),
    ]
