# Generated by Django 5.0 on 2024-02-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_remove_evento_aprovada_remove_evento_sala'),
        ('home', '0007_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='sala',
            field=models.ManyToManyField(to='home.sala'),
        ),
    ]
