# Generated by Django 5.0 on 2024-02-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_evento_aprovada_evento_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
