# Generated by Django 5.0 on 2024-02-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0005_evento_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="cor",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
