# Generated by Django 5.0 on 2024-02-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0007_alter_evento_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="usuario",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
