# Generated by Django 5.0 on 2024-02-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sala_events_aprovada_horarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='horarios',
            field=models.CharField(choices=[('1', '09:30,12:00'), ('2', "12:00',15:30"), ('3', '15:30,19:30'), ('5', '19:30,21:30'), ('6', '15:30,21:30')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
