# Generated by Django 5.0 on 2024-02-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_horarios_usuario_events_sala_remove_sala_horarios_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
