# Generated by Django 5.0 on 2024-02-09 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_horarios_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
