# Generated by Django 5.0 on 2024-02-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="horario",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "09:30 - 12:00"),
                    ("2", "12:00 - 15:30"),
                    ("3", "15:30 - 19:30"),
                    ("4", "19:30 - 21:30"),
                    ("5", "15:30 - 21:30"),
                ],
                max_length=55,
                null=True,
            ),
        ),
    ]
