# Generated by Django 5.0 on 2024-02-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_horario_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="cor",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
