# Generated by Django 5.0 on 2024-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_sala_cor"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorarioBloqueado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario_inicio", models.TimeField()),
                ("horario_fim", models.TimeField()),
                ("motivo", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"verbose_name_plural": "Horários Bloqueados",},
        ),
    ]
