# Generated by Django 5.0 on 2024-02-28 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_horariobloqueado"),
    ]

    operations = [
        migrations.DeleteModel(name="HorarioBloqueado",),
        migrations.RemoveField(model_name="sala", name="cor",),
    ]
