# Generated by Django 5.0 on 2024-03-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_delete_horariobloqueado_remove_sala_cor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sala",
            name="cor",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
