# Generated by Django 5.0 on 2024-03-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_sala_cor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("response", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={"db_table": "tblquestions",},
        ),
    ]
