# Generated by Django 5.0 on 2024-03-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_faq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="response",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
